### ISSUE TITLE
Hacer casos de uso y diagramas de secuencia

### ISSUE THREAD

**Issue by randres-arcila** [calidadudea/Diseno#5]
Yo como diseñador quiero desarrollar los casos de uso y los diagramas de secuencia que describirán la funcionalidad de la aplicación.

**Comment by SebasPelaez** [comment]
Se subió el documento con los diagramas de casos de uso y secuencia.

**Comment by DiegOliveros** [comment]
@SebasPelaez y equipo, 
Favor estimar las historias antes de trabajar en ellas y subir los soportes antes de cerrar.
